services:

  mysql:

    image: mysql:8.4

    container_name: lumiere_mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./banco/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s



  app:

    build: .

    container_name: lumiere_app

    ports:
      - "5000:5000"

    env_file:
      - .env

    volumes:
      - .:/app

    depends_on:
      mysql:
        condition: service_healthy

    restart: always


volumes:
  mysql_data: